### ISSUE TITLE
Digital Learning for Diverse Learners (on both ends of the academic spectrum)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#105]
Google Spreadsheet Row Number: 58

Facilitator:

name: Gina  Tesoriero
twitter: @@STEMsuccessEDU
organization: New York City Department of Education (NYC DOE)

Description:
Participants in this session will be able to identify obstacles that they encounter working with diverse learners on both ends of the academic spectrum, discuss solutions to engage diverse learners in digital learning and learn about best practices that have been used to engage students on both ends of the academic spectrum. The group will then work on how to set goals for implementation into each participants individual programs and develop a community of educators seeking to engage diverse learners that can support each other in the future

**Comment by simonaramkisson** [comment]
@jvallera

**Comment by jvallera** [comment]
@simonaramkisson yes! OF COURSE!

**Comment by emmairwin** [comment]
cc /@emmairwin @geroter good training opportunity for edu leadership in community

**Comment by simonaramkisson** [comment]
**[ Google Spreadsheet Row Number ]** 58
**[ Facilitator ]** Gina  Tesoriero

### Description

Participants in this session will be able to identify obstacles that they encounter working with diverse learners on both ends of the academic spectrum, discuss solutions to engage diverse learners in digital learning and learn about best practices that have been used to engage students on both ends of the academic spectrum. The group will then work on how to set goals for implementation into each participants individual programs and develop a community of educators seeking to engage diverse learners that can support each other in the future

### Agenda

Agenda: 
- Small group brainstorm of obstacles that have been encountered while working with diverse learners/ chart obstacles
- best practices presentation from NYC special education & gifted and talented teacher
- gallery walk of obstacles/ participants suggest solutions to obstacles
- group discussion of obstacles and suggestions 
- implementation plan share out

### Participants

For groups of 15- 150 the agenda will go as planned because participants will be broken up into small groups to work. With less than 15 people the agenda will become more personalized to the specific needs of the participants. For example, if the majority of the participants work with students that are English Language Learners then the main focus will be on strategies to support those learners and the workshop will be more whole discussion rather than small group.

### Outcome

Participants will develop an implementation plan and will be able to offer other participants suggestions from their personal rolodex of best practices.
