### ISSUE TITLE
Learning Game / Explorable Explanations Prototyping Jam

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#160]
**[ Google Spreadsheet Row Number ]** 110
**[ Facilitator ]** Joe Dytrych
### Description

We'll create paper prototypes of learning games (like Erase All Kittens https://eraseallkittens.com) and explorable explanations (like Parable of the Polygons http://ncase.me/polygons/). We'll share a bunch of ideas about designing playful learning thingies, and hopefully learn a bunch of stuff from each other.
### Agenda

We'll start by looking at a couple of examples of learning games and explorable explanations, think about why they work and how they've been designed. Then, we'll generate some of our own ideas, before splitting into smaller groups to create paper prototypes.
### Participants

With 5 participants, we'll work to create 1 or 2 prototypes, with members of the Drum Roll team working with each group.
With 15 participants, we'd aim for 3 or 4 prototypes. Drum Roll team members would rotate round the groups, offering help and trying to keep people on-schedule along the way.
With 50 participants, WE MAKE ALL THE PROTOTYPES AND TAKE OVER THE WORLD.
### Outcome

Depending on the skill sets of attendees, it'd be great to see people taking their prototypes further, and publishing them on the web as full-blown learning games / explorable explanations.

**Comment by SomeHats** [comment]
Hello! I'd like to change my proposal to drop the "learning games" and focus on the "explorable explanations". These area a sort of hybrid of a blog post/article/essay and a game, using interaction and play to tell stories and make otherwise dull and complex ideas fun and intuitive. More examples here: http://explorableexplanations.com/

I'm working on a more in-depth description and agenda for this proposal, as it's currently kinda crappy. I'll post to this issue once I have stuff a little more figured out :)

**Comment by chadsansing** [comment]
cc @chadsansing

**Comment by Saallen** [comment]
cc @EPIKhub

**Comment by marcwalsh-zz** [comment]
We appreciated this submission but unfortunately this session does not fit within the narrative of our Space for 2015 - Hope you will submit another session for 2016.
