### ISSUE TITLE
Strengthening workplace inclusion with Webmaker

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#308]
Google Spreadsheet Row Number: 284

Faciliator: 
name: Steph Guthrie 
twitter: @amirightfolks
organization: Tech Girls Canada

name: Saadia Muzaffar 
twitter: @ThisTechGirl
organization: Tech Girls Canada

Description:
The session will guide participants in collaboratively building a teaching kit to serve as a workshop guide for employers, associations or other groups who want to use Webmaker to help staff or community members understand and recognize implicit biases (e.g. gender bias, racial bias, homophobic bias).

**Comment by Saallen** [comment]
cc @simonaramkisson

**Comment by simonaramkisson** [comment]
**[ Google Spreadsheet Row Number ]** 284
**[ Facilitator ]** Steph Guthrie

### Description

The session will guide participants in collaboratively building a teaching kit to serve as a workshop guide for employers, associations or other groups who want to use Webmaker to help staff or community members understand and recognize implicit biases (e.g. gender bias, racial bias, homophobic bias). The teaching kit, targeting adult learners, will contain 3-5 activities that use X-Ray Goggles, Popcorn and Thimble to explore and/or share what it can be like for marginalized people (e.g. women, people of colour, people with disabilities, transgender people) to navigate the organization, industry, or area of practice. By designing activities that examine these themes, session participants will be empowered to use Webmaker to build understanding of how implicit bias impacts their own workplaces and industries, and how we can all intercept it to create more inclusive working communities.

### Agenda

At MozFest 2013 I led a very successful full-day drop-in workshop to build a Girls in Tech Teaching Kit with Webmaker (one activity is featured on teach.mozilla.org). Since this format worked well, I plan to use a similar one this time. As participants drop by my session area, I will share the kit concept and spark creativity by sharing a few activity ideas (or, as the session progresses, activities that are already complete/in development). Participants will share their own ideas and determine which activity they’d like to work on and which role they’d like to play (e.g. writing activity instructions, building an example of an activity’s finished product in Webmaker). Participants get the Etherpad link and are then free to stay nearby or go elsewhere to work on their portion of the kit, pasting the link to their finished component on the Etherpad for editing/remixing by other participants.

### Participants

This format can accommodate any number of participants. Some participants prefer to work on their kit components in small groups, while others prefer to work independently, and the session can accommodate either. With five participants, each participant will outline one activity in detail and go as far as possible in the time they have to create an example of the activity’s finished product. As the number of participants grows to 15, multiple participants can work on each activity and parse the work into smaller chunks (e.g. one person outline activity steps, one person draft materials checklist and learning outcomes, one person create example Thimble). With 50 people, participants could remix each other’s activities to create additional variations and examples for different learning types and levels. 

### Outcome

This session aims not only to generate a high-quality learning resource, but a community that will support its global dissemination, implementation and iteration. We will encourage all participants to approach at least one employer or organization in their own communities to run a workshop using the teaching kit (or one of the kit activities). Based on their experiences, they can remix the activities and share tips with the group regarding what worked well and what needed fine-tuning. Tips and iterations can be curated and compiled to create a new edition of the teaching kit each year.
