### ISSUE TITLE
[Pathway] Seeing–Drawing–Producing Smilies

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#35]
This pathway will introduce a (graphic) design process – seeing, drawing, producing – through the art of “Ways of Seeing” places we interact in. We will search for faces-in-places (examples of faces-in-places: http://facesinplaces.blogspot.com/) in and around MozFest spaces and places and photograph as many faces we can find. After reviewing and choosing our favourite face-in-place we will draw or transfer this face onto paper. We will further design this face and then digitalise the emoticon icons in vector graphics. Smiling, sad, bewildered, angry, annoyed, surprised, cheeky, etc. faces will be transformed into icons and (hopefully) proudly uploaded to our social media as profile images. The process will be complete when we will see a(t least) three-step process: 1) photograph of a face-in-place, 2) a drawing of that face as a “smiley”, and 3) production of digital emoticon icon.
- [x] #42 
- [x] #43 
- [x] #44

**Comment by metodb** [comment]
cc @metodb

**Comment by metodb** [comment]
Fore more information about the "Seeing–Drawing–Producing Smilies" you can ask me here: @metodb

**Comment by metodb** [comment]
Learning objective of this pathway

This pathway will introduce a (graphic) design process – seeing, drawing, producing – through the art of “Ways of Seeing” places we interact in. We will search for faces-in-places (examples of faces-in-places: http://facesinplaces.blogspot.com) in and around MozFest spaces and places and photograph as many faces we can find. After reviewing and choosing our favourite face-in-place we will draw or transfer this face onto paper. We will further design this face and then digitalise the emoticon icons in vector graphics. Smiling, sad, bewildered, angry, annoyed, surprised, cheeky, etc. faces will be transformed into icons and (hopefully) proudly uploaded to our social media as profile images. The process will be complete when we will see a(t least) three-step process: 1) photograph of a face-in-place, 2) a drawing of that face as a “smily”, and 3) production of digital emoticon icon.

Your Participant Persona(s)

The “Seeing–Drawing–Producing Smilies” pathway introduces a design process to expand your visual literacy while creating a “smily” emoticon icons. It is designed for participants who are eager to work on their visual literacy through a hands-on approach from photography to graphic design. Since visual literacy has no borders this pathway invites participants from all ages, professions, backgrounds or nationalities. Participants are professionals, enthusiasts or flirtatious newbies in the field of graphic design who want to challenge themselves in expanding and/or sharpening their visual understanding – seeing, perceiving, interpreting – of the places we interact in. The pathway welcomes as many interested participants in learning that graphic design process. This pathway is fun through learning while encouraging the participants to engage their right side of the brain.

For more information please don't hesitate in getting in touch here (@metodb) or Twitter: @metodb
