### ISSUE TITLE
Think Like a Programmer, Design Like a Change Agent

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#357]
Google Spreadsheet Row Number: 333

Facilitator:

name: Kimberly A. Scott, Ed.D.
twitter: @cgest_asu
organization: Center for Gender Equity in Science and Technology, Arizona State University
name: Robin Baskin McNulty, M.Ed.
twitter: @cgest_asu
organization: Center for Gender Equity in Science and Technology, Arizona State University

Description:

Participates will learn about the mission and vision of our Center and the need for serving underrepresented girls and women in science, technology, engineering, and mathematics (STEM).
Attendees will develop and execute a personalized social media message and create a global call to action.

**Comment by jvallera** [comment]
@simonaramkisson @jvallera

**Comment by simonaramkisson** [comment]
Goal is to create a global call to action.

### Agenda

Interactive Session

First, the Executive Director of the Center will share our vision and mission and provide data on the need for serving underrepresented girls and women in STEM. 

Second, the Project Coordinator will lead an exercise through which she makes a call to action to the attendees so that they develop personalized social media messages to become agents of change. Attendees will be asked to use the technology on them to produce these items. A laptop will be made available for those that need a tool.

Third, attendees will have the option to report out and have a Q&A with the presenters.

Fourth, an extension activity is planned to engage attendees in the Youth Maker Party.

### Participants

Interactive session and activity lends it self to be productive with any number of attendees. 

### Outcome

1) An increased global awareness of issues faced by underrepresented girls and women in STEM.

2) An increased knowledge of systems based and solution oriented programs such as CompuGirls (an evidence based research program).

3) An increased motivation to advocate and be change makers for girls and women in STEM in their communities.
