### ISSUE TITLE
Models and Modes of Engagement for Authentic Youth Leadership in Informal Digital Learning Contexts

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#366]
Google Spreadsheet Row Number: 346

Facilitator: 
name: Ariam Mogos
twitter: @aamogos
organization: Global Kids 

Description:

Government agencies, learning institutions, international organizations and other stakeholders have sought to leverage digital learning environments to promote youth leadership and civic engagement. While some of these platforms have been successfully employed, cultivating genuine youth participation often comes with challenges.This interactive workshop is designed to provide participants with the opportunity to contribute to an open educational resource for authentic youth leadership.

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by Zebetus** [comment]
@EPIKhub if this is altered so that it looked at getting youth imput into this it could be really cool to sign post towards

**Comment by simonaramkisson** [comment]
**[ Google Spreadsheet Row Number ]** 346
**[ Facilitator ]** Ariam Mogos

### Description

Government agencies, learning institutions, international organizations and other stakeholders have sought to leverage digital learning environments to promote youth leadership and civic engagement. These include youth councils, hack-a-thons, media campaigns and peer education initiatives. While some of these platforms have been successfully employed, cultivating genuine youth participation often comes with challenges. These challenges have illustrated the need for a general framework for models and modes of engagement around youth leadership, which educators and other practitioners can test, remix and adapt. In this interactive session, we will create the space for MozFest participants to share experiences, learn new strategies and collaborate to produce best practices that foster authentic youth leadership.

### Agenda

This interactive workshop is designed to provide participants with the opportunity to contribute to an open educational resource for authentic youth leadership. The session will open with an introduction to the topic and associated challenges. Facilitators will then help orient the group with “essential questions.” Participants will partner up to respond to prompts provided by the facilitators, and engage in a large group post-it activity. Participants will be invited to a gallery style walk of the post-its to discover common trends and themes, followed by whole group discussion. Whole group discussion will lead into brainstorming to develop resources for the wiki. Once sections for the wiki have been identified, participants will break out into small groups to brainstorm resources for each section. The session will wrap-up with a reflection/share-out exercise, in addition to further details on how participants can stay involved in the development of the wiki.

### Participants

The number of participants will not affect the format of the session and can be easily accommodated. If necessary, facilitators can create larger groups during the break-out time and 3-4 participants can partner rather than 2.

### Outcome

The core outcome of this session is an editable wiki which outlines various models and modes of engagement around youth leadership, highlighting a select number of frameworks. Sections of the wiki will also include best practices, challenges, case studies, additional external resources and contact information for participants who can lead further discussion on the topic based on their interest and experience. With the support of the Mozilla community, we hope the wiki will be widely circulated and promoted as an excellent resource for educators.
