### ISSUE TITLE
Building open resources for women at risk

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#384]
Google Spreadsheet Row Number: 360
Facilitator: 

name: Hera Hussein
organization:Chayn
twitter: @chaynorg

Description:
This workshop will showcase some of the innovative work Chayn has been doing with openly licensed toolkits, platforms and hackathons to tackle violence against women from India, Pakistan to UK & Lebanon. In our experience, the empowerment movement is not making the impact possible because charities are reluctant to use, distribute or create openly licensed work. The latter part of the workshop will be a session of creative collaboration to brainstorm ways to push the use of open source materials that we or other organisations have produced with a focus on humanitarian work.

**Comment by simonaramkisson** [comment]
@simonaramkisson

**Comment by simonaramkisson** [comment]
**[ Google Spreadsheet Row Number ]** 360
**[ Facilitator ]** Hera Hussain

### Description

The goal of this session is to showcase how open culture can be used to transform the traditional NGOs that work with vulnerable communities. People will learn how to use their technical knowledge & civic tech experience to empower marginalised and oppressed groups. 

### Agenda

Format: Workshop

This workshop will showcase some of the innovative work Chayn has been doing with openly licensed toolkits, platforms and hackathons to tackle violence against women from India, Pakistan to UK & Lebanon. In our experience, the empowerment movement is not making the impact possible because charities are reluctant to use, distribute or create openly licensed work. The latter part of the workshop will be a session of creative collaboration to brainstorm ways to push the use of open source materials that we or other organisations have produced with a focus on humanitarian work.

### Participants

5 participants - More discussion and shorten the beginning show and tell.
15 participants - The agenda remains unchanged.
50 participants - Longer brainstorm!

### Outcome

We want to take the best of the Mozilla movement and take those learning, projects and resources out to the NGOs that are still quite isolated.
