### ISSUE TITLE
Using crafts to teach localization processes

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#415]
**[ Google Spreadsheet Row Number ]** 401
**[ Facilitator ]** Mohomodou Houssouba
### Description

Participants of different ages – hopefully with a sizable number of children – will join in a creative project which involves playing with the Songhay language and cultural heritage through visual aids. At first glance, the exercise involves exploring an unfamiliar language, one they would rarely know about before joining this session. They will work in pairs or groups to put together letters into words, words into phrases and even simple sentences, match some words and phrases with images or situations that they encounter on worksheets. There is no right or wrong answer. If someone insists that his/her word exists in Songhay, they can prove it by using a dictionary. If the word doesn't appear, it may still exist; since the dictionary is still not fully developed like one in English. In all, the playful interaction with a language and its imagery is the at heart of this session.   
### Agenda

The session is conceived as a workshop but it could also work in an open space. I will bring along worksheets with letters, words and phrases; dictionaries and glossaries; images to match and pieces for a puzzle; sounds that wrap the participants in a special environment. Minimal equipment needed on site: mobile boards to hang pieces, if possible a beamer to project images across a large room or to free-moving groups in an open space, sound system. Continuous motion and hands-on participation are expected throughout the session. Participants create their words in the end, and the fun is to find a meaning for their creations by using the dictionaries and asking me. 
### Participants

The session can be easily adjusted to small and larger groups. For example, 5 children can do a workshop on learning Songhay by matching letters with different patterns of weaving (palm-leaf mats and fans, leather rugs) and animal hides (cows, goats, sheep). A mixed group of 15 will share different images and worksheets to put together different segments of a puzzle. With 50 or more, we will create a core group (about 20) and use the rest as a public or jury. To be sure, this is a free-flowing, open-ended activity, which people can join at different levels or leave whenever they wish. The format is sufficiently flexible because the session is geared toward a young and curious public that is not necessary directly involved in localization. Still children today come across music, images and stories from other countries early on and relate to the diversity in the world.
### Outcome

We would like participants to experience and appreciate the capacity of African languages to express beauty to the ear (poetry) and to the eye (art and craft). All around, they will hear short texts being read in Songhay, see images matching with letters, words and phrases, grapple with special characters and sounds and unfamiliar images. This immersion enables them to feel the complexity of each language, with a rich vocabulary in one area (50-100 possible combinations for cow patterns) and a limited terminology in another (computing terms). The participants experience directly the challenge of localizing a term across languages and cultures.  The experience will be documented through a short report; the results  will be presented to localization trainees in Africa as an illustration of the intercultural dynamics of their work, the creative process involved and the flexibility needed to make culturally relevant translations out of technical tasks.

**Comment by hjbailey** [comment]
This is one we definitely want to include in our space.

**Comment by metodb** [comment]
@hjbailey great you find my pathway of interest ;) Will add all required info of the PW @Saallen is asking for by Wed 23. Sep. Will produce an example image too so people will see the process in 3 steps straight on.

**Comment by metodb** [comment]
Seeing–Drawing–Producing Smilies (by @metodb)

Learning objective of this pathway

This pathway will introduce a (graphic) design process – seeing, drawing, producing – through the art of “Ways of Seeing” places we interact in. We will search for faces-in-places (examples of faces-in-places: http://facesinplaces.blogspot.com) in and around MozFest spaces and places and photograph as many faces we can find. After reviewing and choosing our favourite face-in-place we will draw or transfer this face onto paper. We will further design this face and then digitalise the emoticon icons in vector graphics. Smiling, sad, bewildered, angry, annoyed, surprised, cheeky, etc. faces will be transformed into icons and (hopefully) proudly uploaded to our social media as profile images. The process will be complete when we will see a(t least) three-step process: 1) photograph of a face-in-place, 2) a drawing of that face as a “smily”, and 3) production of digital emoticon icon.

Your Participant Persona(s)

The “Seeing–Drawing–Producing Smilies” pathway introduces a design process to expand your visual literacy while creating a “smily” emoticon icons. It is designed for participants who are eager to work on their visual literacy through a hands-on approach from photography to graphic design. Since visual literacy has no borders this pathway invites participants from all ages, professions, backgrounds or nationalities. Participants are professionals, enthusiasts or flirtatious newbies in the field of graphic design who want to challenge themselves in expanding and/or sharpening their visual understanding – seeing, perceiving, interpreting – of the places we interact in. The pathway welcomes as many interested participants in learning that graphic design process. This pathway is fun through learning while encouraging the participants to engage their right side of the brain.

–––––––––––––––
For more information please don't hesitate in getting in touch here (@metodb) or Twitter: @metodb

**Comment by Zebetus** [comment]
@EPIKhub Maybe we can help out with making sure they get they get lots of youths involved??

**Comment by hjbailey** [comment]
This is a great place for the Youth Zone to participate and we would encourage lots of cross over between this session and yours.

**Comment by EPIKhub** [comment]
@hjbailey If a session is not rejected you need to NOT close it, all CLOSED sessions are considered rejected cc/ @Saallen

**Comment by Saallen** [comment]
hey @hjbailey is this session taking place in your space? If not please remove your milestone- thanks

**Comment by hjbailey** [comment]
This is taking place in my session.

**Comment by metodb** [comment]
Hello @hjbailey, we are talking about my pathway "Seeing–Drawing–producing Smilies". How would be best getting in touch? Here is my email: metodb@yahoo.com

**Comment by ArtsAward** [comment]
@EPIKhub looks like a pathway for Arts Award, please add to your list of relevant pathways out from the Youth Zone
