### ISSUE TITLE
Visual basics 

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#42]
Experience one is to work with visual basics – how to see when we are looking. We will adjust our eye-shift to focus on finding faces in the most unexpected places – those seen in a bin, sink, walls, street furniture, etc. (people’s or animal faces do not count). We will be photographing as many of these found faces-in-places as we can in and around MozFest spaces and places and later choose our favourite. The experience one photography activity will require about 4–5h (bot not necessarily fully engaged) to photograph the found faces.

**Comment by metodb** [comment]
Drawing these Smilies (instead of "Visual Basics")
We will review our found faces-in-places we photographed and choose the favourite “smily” (or any other emotion-full face). We will draw and/or transfer the face(s) from our photographs onto paper using pencils, pens, ball pens, markers, etc. and prepare it for our last session.

> Metod Blejec / @metodb (Twitter)
> Session 2/3 — Saturday PM (15:00)
