### ISSUE TITLE
Digitalise your Icons

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#44]
In the final experience three we will take our drawings and hand drawn designs from experience two and digitalise the "smiley" icons by either tracing them or digitally recreate them in a simple monochrome vector graphic technique. We will then start playing with colour, framing, spacing and other design principles. For the experience three design production session we will need 1–2h while using computer applications (Illustrator, Inkscape, etc.) to draw our “smiley” emoticons in vector graphics and finally export them as images for social media upload.

**Comment by metodb** [comment]
Digitalise Smiley Icon (instead of "Digitalise your icons")
Faces-in-places drawings will help us digitalise these smilies into vectors. We will trace or digitally recreate them in a vector graphic on the computer (using Illustrator, Inkscape, etc.). Then we will play with colour, framing, spacing and other design principles. Voila, smiley icon is done! Lets upload it.

> Metod Blejec / @metodb (Twitter)
> Session 3/3 — Sunday AM (11:00)
