### ISSUE TITLE
[Pathway] Storytellers & coders united: together we can change the world!

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#466]
Pathfinder-  Sandra Gaudenzi
The pathway is for:
- storytellers (content people) that do not have coding skills (journalists, documentary makers, social activists, NGO campaigners...) - NB: we are speaking of factual stories (online news, web docs, games for change etc...) so stories that are trying to inform and change the world.
- creative technologists interested in interactive stories for good (designers, coders, user experience specialists...)

Those two groups at the moment find it hard to:
- be in contact (lack of networking opportunities)
- work together (different languages, know hows and methodologies of work)
- co-create together from the beginning of a project (often technologists are called on board only once the project has been defined)

The motivation for the pathway is to bring them together during the sessions and:
- start establishing a dialogue
- make something together
- get excited about the strengths of their complementary skills
- bridge the gap and invent new initiatives outside of MozFest to foster more opportunities for collaboration

Why should they participate?
- Creative technologists might want to "feel useful" by investing some of their time in meaningful projects that are trying to change the world for the better, in a small or big way
- Storytellers wants to get in contact with creative technologists but do not know how, nor where to find them
- interactive narratives are a new form: everybody interested in this form is looking for opportunities to brainstorm, and try, new ways of co-creation, so this pathway would offer such opportunity.
- [x] #467 
- [x] #468 
- [x] #469

**Comment by digitalSG** [comment]
Pathfinder- Sandra Gaudenzi

PERSONAS:

The pathway is aimed at:
- storytellers (content people) that do not have coding skills (journalists, documentary makers, social activists, NGO campaigners...). We are speaking of factual stories (online news, web docs, games for change etc...) so stories that are trying to inform and change the world.
- creative technologists interested in interactive stories for good (designers, coders, user experience specialists...)

Those two groups of people at the moment find it hard to:
- be in contact (lack of networking opportunities)
- work together (different languages, know hows and methodologies of work)
- co-create together from the beginning of a project (often technologists are called on board only once the project has been defined)

LEARNING OUTCOMES:

The motivation for the pathway is to bring storytellers and creative technologists together during the sessions and:
- start establishing a dialogue
- make something together
- get excited about the strengths of their complementary skills
- bridge the gap and invent new initiatives outside of MozFest to foster more opportunities for collaboration

Why should they participate?
- Creative technologists might want to "feel useful" by investing some of their time in meaningful projects that are trying to change the world for the better, in a small or big way.
- Storytellers wants to get in contact with creative technologists but do not know how, nor where to find them.
- Interactive narratives are a new form: everybody interested in this form is looking for opportunities to brainstorm, and try, new ways of co-creation, so this pathway would offer such opportunity.

STRUCTURE:

The pathway is organised in such a way that discussion, active collaboration and curiosity around interactive factual stories is stimulated. Three sessions have been designed to progress into this discovery journey:
1. Let's challenge the way interactive stories are  changing the world.
   This session is aimed introducing the field of interactive factual storytelling and solving together some salient issues. See #467 for more info. 
   Ideally this session would be held on the Saturday.
2. Let's bridge the gap between storytellers and technologists
   This session is aimed at consolidating the collaboration that was started in #467 by asking participants to brainstorm ideas to build a platform that will allow them to keep working together in the future. See #468 for more info.
   Ideally this session would be held on the Sunday.
3. Inspiration time: explore recent projects that will change the way you understand the world
   For this session 3/4 existing web projects will be on show on a computer, so that people can explore for themselves this new type of narrative and make up their mind about it. See #469 for more info.
   This is an ongoing session that is available during the whole festival. A Q&A session of 1 hr with the authors of the Digital Me project could be organised as they are both attending MozFest.

**Comment by marcwalsh-zz** [comment]
From: @cubicgarden -  Like to have a aspect of this running through the library. I'm about to put a proposal down for the Perceptive Radio v2, with workshop which could fit this pathway perfectly.

**Comment by digitalSG** [comment]
150 words DESCRIPTIVE TEXT: 

If you want to work on projects that can change the world, and wondered how to use interactive stories to do so, then this pathway is for you!
In “Storytellers and coders united: together we can change the world!” we want developers, creative technologists and content specialists (journalists, documentary makers, gamers for change, photographers, social activists etc...) to get excited about using interactivity to transform users into active facilitators of change. 
Together, we will challenge storytelling rules and create new interfaces and new interaction dynamics that will challenge what has been done so far. We will inspire you with examples of great recent projects and will brainstorm possible platforms that will allow us to keep working together after MozFest. 
This is a pathways for people that want to use their skills to contribute to meaningful projects, while pushing boundaries, working collaboratively and having fun.
