### ISSUE TITLE
Wizards "RULE" - CodeSpell code your own JAVA spells

### ISSUE THREAD

**Issue by EPIKhub** [mozilla/mozfest-program#549]
[ Google Spreadsheet Row Number ] 
[ Facilitator ] Tennyson Holloway

Video on Codespell: https://vimeo.com/user30461369

This really interesting computer game teaches Java coding through playing a wizard, where the limit is your imagination, possibly the next step from "MineCraft"?

CodeSpells is a game that lets you modify your spells using Blockly or Javascript and teaches common coding patters along the way. I learned to code by modifying and hosting an MMORPG private server, where I was able to change the gamerules using code. This allowed me to be creative; I was able to express myself through changing the game world and rules. For me, and many others, the desire to mod games is very strong, and for the first time, it is very accessible. With projects like Codespells that are designed to be modified, the opportunities for exploration, learning, creative inquiry, etc, are endless.
What will your session or activity allow people to make, learn or do?

This session will introduce players to Codespells, a game where you craft magical spells with code. Players will be able to sit down and experience the latest beta version of the game, and will be able to explore and complete challenges using their creative spells.
How do you see that working? Describe your session’s agenda in 150 words or less. Please also describe the format of the session.

From my understanding, there will be computers there preloaded with Codespells. I used to work for the creators of Codespells, so I might be able to get a custom mozfest version that is preloaded with some interesting courses and challenges. The format will be a quick introduction followed by an hour of in-game time.
How will you accommodate varying number of participants in your session? Tell us what you'll do with 5 participants. 15? 50? In 150 words or less.

As more participants arrive, they will be able to pair-up on the available computers for pair-programming.
What do you see as outcomes after the festival? How will you and your participants take the learning and activities forward? In 150 words or less.

I hope for players to be able to come to the Codespells discussion forum and continue their magical journey in having fun while learning essential skills, like teamwork and analytical thinking. The discussion forum is a safe environment of other witches and wizards who all want to create the most impressive spells possible.
If the session is successful, participants will do the following after

Mozfest:
Participants will see that modding and hacking games is both extremely fun/rewarding, and within their reach

**Comment by EPIKhub** [comment]
@Saallen @MozStacy cost of flight is to high from Washington so can't come and I have no one else to run it 😔 so will close it

**Comment by EPIKhub** [comment]
@Saallen @MozStacy Tennyson will be our new leader on this session, great choice :)

**Comment by m4chinations** [comment]
@EPIKhub @MozStacy 

Hey all, here is a revised session submission (it's a little thin since I've rushed it):

The general idea behind this session is introducing Codespells in the youth zone at MozFest. CodeSpells is a game that lets you modify your spells using Blockly or Javascript and teaches common coding patters along the way. I learned to code by modifying and hosting an MMORPG private server, where I was able to change the gamerules using code. This allowed me to be creative; I was able to express myself through changing the game world and rules. For me, and many others, the desire to mod games is very strong, and for the first time, it is very accessible. With projects like Codespells that are designed to be modified, the opportunities for exploration, learning, creative inquiry, etc, are endless. 

# What will your session or activity allow people to make, learn or do?

This session will introduce players to Codespells, a game where you craft magical spells with code. Players will be able to sit down and experience the latest beta version of the game, and will be able to explore and complete challenges using their creative spells. 

# How do you see that working? Describe your session’s agenda in 150 words or less. Please also describe the format of the session.

From my understanding, there will be computers there preloaded with Codespells. I used to work for the creators of Codespells, so I might be able to get a custom mozfest version that is preloaded with some interesting courses and challenges. The format will be a quick introduction followed by an hour of in-game time.

# How will you accommodate varying number of participants in your session? Tell us what you'll do with 5 participants. 15? 50? In 150 words or less.

As more participants arrive, they will be able to pair-up on the available computers for pair-programming. 

# What do you see as outcomes after the festival? How will you and your participants take the learning and activities forward? In 150 words or less.

I hope for players to be able to come to the Codespells discussion forum and continue their magical journey in having fun while learning essential skills, like teamwork and analytical thinking. The discussion forum is a safe environment of other witches and wizards who all want to create the most impressive spells possible.

# If the session is successful, participants will do the following after

Mozfest:
Participants will see that modding and hacking games is both extremely fun/rewarding, and within their reach
